### ISSUE TITLE
加密视频无法自动合并吗

### ISSUE THREAD

**Issue by hiliving** [JeffMony/VideoDownloader#13]
试了demo，加密的视频链接无法自动合并呢

**Comment by JeffMony** [comment]
发一下例子阿

**Comment by hiliving** [comment]
> 发一下例子阿

https://mu.qqxy100.com/ts/2/24643512205049856/index.m3u8?wssecret=c6df5611dabc5a4846342e75f798cac1&wstime=1604025000&

日志：
`2020-10-30 12:33:54.171 4132-4240/com.jeffmony.videodemo I/VideoDownloadManager: VideoMerge doMergeTs taskItem=VideoTaskItem[Url=https://mu.qqxy100.com/ts/2/24643512205049856/index.m3u8?wssecret=c6df5611dabc5a4846342e75f798cac1&wstime=1604025000&,Type=1,Percent=100.0,DownloadSize=951448822,State=5,FilePath=local.m3u8,LocalFile=/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/b69061a7a69b520f408cd24356405264/local.m3u8]
2020-10-30 12:33:54.191 4132-4240/com.jeffmony.videodemo I/VideoDownloadManager: VideoMerge onMergeFailed e=java.lang.Exception: Merge ts failed
2020-10-30 12:50:02.724 4132-4240/com.jeffmony.videodemo W/VideoDownloadManager: removeDownloadQueue size=0,0,0`

是因为ffmpeg不支持吗

**Comment by hiliving** [comment]
我先用Java做解密、合并了，楼主如果解决了可艾特我一下
