### ISSUE TITLE
部分资源下载合并后很多播放器不能播放，只有个别播放器可以播

### ISSUE THREAD

**Issue by hiliving** [JeffMony/VideoDownloader#14]
测试
https://tx.79da.com/data/tx/5f88c1a1bf9cac7ab9b42031.m3u8

使用ffmpeg合并ts后
测试播放器，x5内核sdk内置的tbs播放器，播放有画面，无声音，自己对接的playBase播放器，也是有画面无声音。
使用QQ浏览器的播霸可以正常播。

使用Java代码(字节流拼接)合并ts后，所有播放器均可正常播放。

猜测是ffmpeg拼接后做了转码处理，这个部分我不太懂，楼主有空可查看一下，如需提供更多测试地址可邮件我1195996300@qq.com

**Comment by JeffMony** [comment]
ts拼接完了还是ts啊,并没有变成mp4视频的
