### ISSUE TITLE
更新之后mp4下载速度乱飘

### ISSUE THREAD

**Issue by kxbyte** [JeffMony/VideoDownloader#19]
更新之后mp4下载速度乱飘，有时候能到70多MB，实际下载速度基本在每秒2-3MB

下载地址：https://rrsp-1252816746.cos.ap-shanghai.myqcloud.com/0c1f023caa3bbefbe16a5ce564142bbe.mp4

**Comment by JeffMony** [comment]
好的, 这个我看一下.

**Comment by JeffMony** [comment]
我下载的速度很好啊, 新版本的修改就是为了解决下载速度乱飘的问题的.

**Comment by kxbyte** [comment]
https://user-images.githubusercontent.com/56510194/111328521-462ecf80-86a9-11eb-9e88-0a7872e0ecca.mp4

这个是刚刚最后更新之后的录屏，你看一下
>1c2d92f
