### ISSUE TITLE
下载HLS视频结束异常

### ISSUE THREAD

**Issue by leveychen** [JeffMony/VideoDownloader#2]
两个问题
1. 任何任务结束后 onSpeed 一直回调，不会结束
2. m3u8任务文件内有950个ts切片，下载log显示有951个，导致任务没办法正常走onSuccess，一直处于 onProgress，没办法结束任务。没有成功保存local.m3u8

**Comment by leveychen** [comment]
补充一个，下载HLS的时候，下载速度是不正确的，大部分时候速度处于 0KB/s  但是百分比在走

**Comment by JeffMony** [comment]
好的，持续优化中。

**Comment by JeffMony** [comment]
> 2\. m3u8任务文件内有950个ts切片，下载log显示有951个，导致任务没办法正常走onSuccess，一直处于 onProgress，没办法结束任务。没有成功保存local.m3u8

你下载的m3u8链接是什么啊？

**Comment by JeffMony** [comment]
> 两个问题
> 
> 1. 任何任务结束后 onSpeed 一直回调，不会结束
> 2. m3u8任务文件内有950个ts切片，下载log显示有951个，导致任务没办法正常走onSuccess，一直处于 onProgress，没办法结束任务。没有成功保存local.m3u8

这个问题应该解决了。

**Comment by leveychen** [comment]
filePath 拼接错了
正常应该是
````java
abc/abc.video
````
而目前 filePath  和 fileName 输出均是
````java 
abc/abc/.video
````
多了一个 /

**Comment by JeffMony** [comment]
> filePath 拼接错了
> 正常应该是
> 
> ```java
> abc/abc.video
> ```
> 
> 而目前 filePath 和 fileName 输出均是
> 
> ```java
> abc/abc/.video
> ```
> 
> 多了一个 /

这个没有复现。

**Comment by GXSZone** [comment]
VideoDownloadManager 里
onTaskFinished
```
else if (taskItem.isNonHlsType()) {
                        //    taskItem.setFilePath(taskItem.getSaveDir() + File.separator + taskItem.getFileHash() + File.separator + VideoDownloadUtils.VIDEO_SUFFIX);
                            taskItem.setFilePath(taskItem.getSaveDir() + File.separator + taskItem.getFileHash()+ VideoDownloadUtils.VIDEO_SUFFIX);
    
                            //   taskItem.setFileName(taskItem.getFileHash() + File.separator + VideoDownloadUtils.VIDEO_SUFFIX);
                            taskItem.setFileName(taskItem.getFileHash()+ VideoDownloadUtils.VIDEO_SUFFIX);
    
```
