### ISSUE TITLE
M3U8其中一个下载不了

### ISSUE THREAD

**Issue by aylgyfqc** [JeffMony/VideoDownloader#24]
http://youku.cdn4-okzy.com/20210109/13040_ba1b5858/index.m3u8 
这个下载不了

MediaSDK 和 VideoDownloader 和 JeffVideoCache几个demo都下载不了。

这三个库哪个是最新的写的呀

**Comment by JeffMony** [comment]
[tcp @ 0x7ff8c4003600] Failed to resolve hostname youku.cdn4-okzy.com: Name or service not known
http://youku.cdn4-okzy.com/20210109/13040_ba1b5858/index.m3u8: Input/output error

这个源连通性有问题.

**Comment by JeffMony** [comment]
MediaSDK是下载播放一起的.
VideoDownloader专业下载
JeffVideoCache是专业播放

**Comment by aylgyfqc** [comment]
1
