### ISSUE TITLE
设置ShouldM3U8Merged合并时崩溃

### ISSUE THREAD

**Issue by aylgyfqc** [JeffMony/VideoDownloader#25]
![image](https://user-images.githubusercontent.com/9261470/114177680-47cd7980-996f-11eb-978f-f3da799157e6.png)

**Comment by aylgyfqc** [comment]
val config = VideoDownloadManager.Build(this)
            .setCacheRoot(file.absolutePath)
            .setTimeOut(DownloadConstants.READ_TIMEOUT, DownloadConstants.CONN_TIMEOUT)
            .setConcurrentCount(DownloadConstants.CONCURRENT)
            .setIgnoreCertErrors(true)
            .setShouldM3U8Merged(true)
            .buildConfig()
        VideoDownloadManager.getInstance().initConfig(config)

**Comment by JeffMony** [comment]
你是在demo中运行出这个问题的吗？

implementation 'com.github.JeffMony:JeffFFmpegDemo:1.5.0'
你的工程有没有依赖这个库啊。

**Comment by aylgyfqc** [comment]
忘记回复了，没有在demo里，在自己的工程里
我是直接导入的downloader工程当Module这种方式依赖的，
downloader工程里有依赖JeffFFmpegDemo。

我刚试了下demo里是可以的。自己的工程里不行。

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lypro.flashclearext-QYk-j21fBjXfX7zo4bdRLw==/base.apk"],nativeLibraryDirectories=[/data/app/com.lypro.flashclearext-QYk-j21fBjXfX7zo4bdRLw==/lib/arm, /data/app/com.lypro.flashclearext-QYk-j21fBjXfX7zo4bdRLw==/base.apk!/lib/armeabi, /system/lib]]] couldn't find "libjeffmony.so"

一直有这个错，我再去检查下。

**Comment by JeffMony** [comment]
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lypro.flashclearext-QYk-j21fBjXfX7zo4bdRLw==/base.apk"],nativeLibraryDirectories=[/data/app/com.lypro.flashclearext-QYk-j21fBjXfX7zo4bdRLw==/lib/arm, /data/app/com.lypro.flashclearext-QYk-j21fBjXfX7zo4bdRLw==/base.apk!/lib/armeabi, /system/lib]]] couldn't find "libjeffmony.so"

我demo是直接依赖module， 你依赖线上aar，我用的implementation，并没有使用api，因为使用api会增大一些包大小，只是不想让用不到的开发者增加很多不必要的包大小。
你自己的项目还是要依赖一下JeffFFmpegDemo的

**Comment by aylgyfqc** [comment]
额，我知道你意思。我的工程也是直接依赖的module。并且我也在主工程依赖了com.github.JeffMony:JeffFFmpegDemo:1.5.0，但是还是有这个问题。
应该是我集成了其他东西，或者其他设置导致的这个问题。。
