### ISSUE TITLE
您好,希望您能帮我解答一下 全局只设置一次监听,为何onDownloadSuccess 和 onDownloadProgress 100% 会有多次回调,demo中却不会出现 ?  另外 保存的MP4为什么要以.video结尾

### ISSUE THREAD

**Issue by sagaciousfrog** [JeffMony/VideoDownloader#26]

**Comment by JeffMony** [comment]
1.为什么onDownloadSuccess和onDownloadProcess 100%会回调多次？
因为下载是以多线程下载的，最后回调的时候也在多线程中，所以这些回调可能会回调多次，
我建议你使用这个库的情况下最好做一下限制，例如已经收到了onDownloadSuccess就认为已经下载完成了，后续就不在接收这个回调了。
2.为什么MP4以.video结尾？
我没有区分太多，主要将视频分为两类，M3U8是和非M3U8视频，非M3U8视频都以.video结尾。
