### ISSUE TITLE
下载bug

### ISSUE THREAD

**Issue by shichuanenhui** [JeffMony/VideoDownloader#3]
1.下载进度错乱，同时几个一起下载,有时进度显示有问题
2.全部暂停时候，正在等待中的不会暂停，只会暂停下载中的
3.全部恢复下载只会恢复准备好的，未准备的不会恢复下载（正常使用场景暂时不会出现demo中未下载这个状态，都是从暂停中起始）

**Comment by JeffMony** [comment]
> 1.下载进度错乱，同时几个一起下载,有时进度显示有问题

1.你要会使用方法，全局注册一个监听器，回调中都会实时更新VideoTaskItem，不会存在错乱的情况。

2和3 确实存在，但是简单改一下代码就可以实现。
