### ISSUE TITLE
ts片段合成MP4 中用到的 X86. X86-64位的库会提供吗

### ISSUE THREAD

**Issue by tmphuang6** [JeffMony/VideoDownloader#30]
ts片段合成MP4 中用到的 X86. X86-64位的库会提供吗

**Comment by JeffMony** [comment]
> ts片段合成MP4 中用到的 X86. X86-64位的库会提供吗

有需要稍后就会提供的。

**Comment by tmphuang6** [comment]
OK ..有需要的..商店现在有要求了

**Comment by JeffMony** [comment]
> OK ..有需要的..商店现在有要求了

新版本已经提供了，可以看看是否可以。
