### ISSUE TITLE
m3u8合并为MP4时失败

### ISSUE THREAD

**Issue by windseamless** [JeffMony/VideoDownloader#34]
您好，请问下合并m3u8（调用native函数transformVideo）失败，返回-21是什么原因呢？谢谢！

**Comment by JeffMony** [comment]
具体的m3u8链接贴一下了。

**Comment by windseamless** [comment]
使用的是demo中的地址，具体链接为：https://v3.dious.cc/20201224/v04Vp1ES/index.m3u8 ； 另外想确认下，是否支持m3u8 部分连续ts的合并呢？

**Comment by JeffMony** [comment]
[hls @ 0x7f948485f200] Opening 'https://v3.dious.cc/20201224/v04Vp1ES/1000kb/hls/index.m3u8?skipl=1' for reading
[tcp @ 0x7f948b8bbec0] Connection to tcp://v3.dious.cc:443 failed: Operation timed out
[hls @ 0x7f948485f200] parse_playlist error Operation timed out [https://v3.dious.cc/20201224/v04Vp1ES/1000kb/hls/index.m3u8?skipl=1]
https://v3.dious.cc/20201224/v04Vp1ES/index.m3u8: Operation timed out

无法请求数据啊

**Comment by windseamless** [comment]
换了一个有数据的，指定目录查看存在ts文件，合成mp4时还是失败（结果码仍是-21），请问下返回-21一般是什么原因呢？
PS: 换了其他合成方式，是可以的。

**Comment by JeffMony** [comment]
你过滤一下：FFmpeg_JeffMony 关键字，这个错误是FFmpeg内部错误。

**Comment by windseamless** [comment]
好的，谢谢，我再检查下。
