### ISSUE TITLE
混淆后, 合并m3u8闪退

### ISSUE THREAD

**Issue by yangxiaoge** [JeffMony/VideoDownloader#36]
是否可以提供下,混淆的规则,谢谢.
![image](https://user-images.githubusercontent.com/12471093/146111174-2b3522e9-f12d-4303-ab28-52c304adfb45.png)

**Comment by JeffMony** [comment]
https://github.com/JeffMony/JeffM3U8Lib
这是合并库，可以参考下。

**Comment by yangxiaoge** [comment]
> https://github.com/JeffMony/JeffM3U8Lib 这是合并库，可以参考下。

多谢, 加了混淆后好了!
