### ISSUE TITLE
m3u8转MP4时报错

### ISSUE THREAD

**Issue by dujunandroid** [JeffMony/VideoDownloader#37]
调试发现，在调用initFFmpegOptions方法时报错如下：
E/art: No implementation found for void com.jeffmony.m3u8library.VideoProcessor.initFFmpegOptions() (tried Java_com_jeffmony_m3u8library_VideoProcessor_initFFmpegOptions and Java_com_jeffmony_m3u8library_VideoProcessor_initFFmpegOptions__)
qi请问大佬这个该怎么处理
<img width="432" alt="微信图片_20220114155820" src="https://user-images.githubusercontent.com/7837858/149471899-b467e51d-3738-4f78-a08c-ff70810d8fd5.png">

**Comment by JeffMony** [comment]
混淆呢？

**Comment by dujunandroid** [comment]
> 混淆呢？

目前没做混淆

**Comment by dujunandroid** [comment]
另外我是项目依赖的downloader模块，然后downloader模块依赖com.github.JeffMony:JeffM3U8Lib:1.2.0，我如果将downloader中的依赖改成com.github.JeffMony:JeffFFmpegDemo:1.6.0，编译不通过，会找不到VideoProcessManager类
C:\Users\L14\Documents\apk\downloader\src\main\java\com\jeffmony\downloader\VideoDownloadManager.java:33: 错误: 程序包com.jeffmony.m3u8library不存在
import com.jeffmony.m3u8library.VideoProcessManager;
@JeffMony 请大佬不吝赐教，谢谢

**Comment by JeffMony** [comment]
https://github.com/JeffMony/JeffM3U8Lib
这个合并的代码仓，实在不行可以内置这个代码进你的项目。
