### ISSUE TITLE
这种链接又是一种情况

### ISSUE THREAD

**Issue by GXSZone** [JeffMony/VideoDownloader#4]
>>>bjm3u8

https://hls.aoxtv.com/v3.szjal.cn/20200114/dtOHlPFE/index.m3u8

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=900000,RESOLUTION=1080x276
/20200114/dtOHlPFE/900kb/hls/index.m3u8

最后拼接地址，这种只匹配第一个就不行了
https://`hls.aoxtv.com`/`v3.szjal.cn`/20200114/dtOHlPFE/900kb/hls/index.m3u8

**Comment by GXSZone** [comment]
建议加个合并的功能，ts文件太多，图库里显示出来就太扎眼了

**Comment by JeffMony** [comment]
> 建议加个合并的功能，ts文件太多，图库里显示出来就太扎眼了
这个我考虑过，但是合并存在一定的困难。
1.因为所有的ts的编码格式不一定相同，这样看来合并的时候并不是简单的合并，还加上变码的处理；
2.所以我加上了隐藏文件，防止被看到。

**Comment by GXSZone** [comment]
@JeffMony github上的开源库好像也没对编码处理
