### ISSUE TITLE
Crash when call native code 

### ISSUE THREAD

**Issue by yaoligen** [JeffMony/VideoDownloader#43]
NI DETECTED ERROR IN APPLICATION: mid == null
    in call to CallVoidMethodV
    from int com.jeffmony.m3u8library.VideoProcessor.transformVideo(java.lang.String, java.lang.String):
  #00  pc 0x0000000000051b7c  /apex/com.android.runtime/lib64/bionic/libc.so (abort)
  #00  pc 0x00000000006d29ec  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*))
  #00  pc 0x0000000000016ea8  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*))
  #00  pc 0x0000000000016450  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage())
  #00  pc 0x0000000000445224  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*))
  #00  pc 0x00000000005ddc58  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list))
  #00  pc 0x0000000000001438  /data/app/~~UDf0QWjusBaxWkkIlW81pg==/video.downloader.tiktok.instagram.file.saver.vault-7-eLgJNtJvibjsogVlDMpA==/split_config.arm64_v8a.apk!libjeffmony.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...))
  #00  pc 0x0000000000001a00  /data/app/~~UDf0QWjusBaxWkkIlW81pg==/video.downloader.tiktok.instagram.file.saver.vault-7-eLgJNtJvibjsogVlDMpA==/split_config.arm64_v8a.apk!libjeffmony.so (Java_com_jeffmony_m3u8library_VideoProcessor_transformVideo)
  #00  pc 0x0000000000440554  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline)
  #00  pc 0x000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper)
  #00  pc 0x00000000013f955a  /data/app/~~UDf0QWjusBaxWkkIlW81pg==/video.downloader.tiktok.instagram.file.saver.vault-7-eLgJNtJvibjsogVlDMpA==/oat/arm64/base.vdex (g.n.b.a.run)
  #00  pc 0x00000000007199bc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.Executors$RunnableAdapter.call)

**Comment by JeffMony** [comment]
使用新版本试试看看
