### ISSUE TITLE
无法合并带有#EXT-X-DISCONTINUITY标签的的m3u8文件

### ISSUE THREAD

**Issue by a39717444** [JeffMony/VideoDownloader#46]
例如该网页下的m3u8文件中包含一个#EXT-X-DISCONTINUITY标签，导致文件合并出现如下异常：
视频时长不对，播放到6分20秒出现播放异常（也就是m3u8文件中#EXT-X-DISCONTINUITY衔接的位置）

测试url：
https://v.youku.com/v_show/id_XNTkyMjAxNDAzMg==.html?scene=long&playMode=pugv&albumId=2000534010&sharekey=b424a80e90a4d3a3eb9850736cc18cf46

**Comment by JeffMony** [comment]
带有 #EXT-X-DISCONTINUITY 的文件通常是需要转码的，不然无法合并。
这儿的合并只是简单的解封装，重新封装。

如果需要解码再编码，耗时很长，不太适合这种场景。

针对#EXT-X-DISCONTINUITY视频，我建议有下：
合并的时候剔除#EXT-X-DISCONTINUITY后面的视频。
