### ISSUE TITLE
在合并TS的时候会丢失数据

### ISSUE THREAD

**Issue by sing1** [JeffMony/VideoDownloader#48]
我有一个12秒的数据，下载完后会有一个1.24M的10秒ts和一个496.32k的2秒视频，合并之后会生成一个867k的12秒mp4，但是播放的时候会出现从第4秒直接跳转到11秒的情况，因为我们的m3u8是带auth时效的无法提供，你们有遇到这种情况吗？我的多条链接都出现这种情况

**Comment by JeffMony** [comment]
这种有可能是合成时pts 异常导致的，如果有可能的话，构建一个能复现的M3U8，我验证一下了。

**Comment by sing1** [comment]
> 这种有可能是合成时pts 异常导致的，如果有可能的话，构建一个能复现的M3U8，我验证一下了。

https://vod.soundstage.cn/f7695410d4f371ed8d6c16b5feac0102/video/81eb3c63bfd74856b5d7922b04155f65-4f17abef18d33e3f2151dbde92e4ccbd-video-ld.m3u8?auth_key=1681890446-e93a1a43c99f4d75afad9322c0e8d1cb-0-c328fa251abf466fbf909c12933186b1

**Comment by JeffMony** [comment]
使用最新的包试下了。https://github.com/JeffMony/VideoDownloader/commit/8a4752f0b48970f4b313afca520142b732b6a878
最终合成的视频是正常的：
https://github.com/JeffMony/VideoDownloader/blob/master/files/output.mp4
