### ISSUE TITLE
m3u8视频 部分ts下载失败，能否继续下载？

### ISSUE THREAD

**Issue by ZhuSky** [JeffMony/VideoDownloader#52]
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/18596232/236273704-d8ffeae6-de88-44f0-81cd-89be5d3e00bf.png">

因一个m3u8中 可能存在1-2个ts链接失效（403），直接就Exception停止下载了。能否配置让其继续下载，忽略这1-2个下载失败的问题

**Comment by JeffMony** [comment]
当然可以配置让其继续下载。但是这样不太好，因为一个ts下载失败，最终也是失败，即使后面的都下载成功，某一个ts下载失败，整个M3U8文件还是下载失败的。

**Comment by ZhuSky** [comment]
明白，这种m3u8文件确实属于 失效的，但是目前有这种需求，部分失效，但是依旧算正常类型，只有ts失效超过一个范围（比如5～10），才算失败。我看您的设计 下载成功计算的是下载的长度。请问这里框架设计了吗？没有的话我是不是需要修改 下载成功回掉的计算方式才可以？

**Comment by JeffMony** [comment]
ts失效超过一定的范围？加入是5个ts失效，那这个是指连续5个ts失效，还是指总共加起来5个ts失效了？

**Comment by ZhuSky** [comment]
连续的

**Comment by ZhuSky** [comment]
因为在 ijkPlayer中，这样的数据属于有效视频，所以下载器同样需要对应

**Comment by JeffMony** [comment]
这个属于比较定制的修改，没有统一的标准，有人觉得需要保证所有ts下载成功，有人觉得可以允许几个ts下载失败，你可以在代码中自己定制一下。

**Comment by ZhuSky** [comment]
好的明白了 感谢大佬
