### ISSUE TITLE
加密的ts文件怎么合成mp4 这个问题困扰很久 请求大佬解惑

### ISSUE THREAD

**Issue by sengechupin** [JeffMony/VideoDownloader#54]

**Comment by JeffMony** [comment]
加密的TS是可以合并的，你不能合并的例子是什么？发一下我看下。

**Comment by sengechupin** [comment]
发你邮箱了

**Comment by sengechupin** [comment]
Error when loading first segment '/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/3ce57817f3c4e0cc437a66a25db76b45/video_0.ts'
Could not open input file '/storage/emulated/0/Android/data/com.jeffmony.videodemo/files/Video/Download/3ce57817f3c4e0cc437a66a25db76b45/3ce57817f3c4e0cc437a66a25db76b45_local.m3u8'
Error occurred: Invalid data found when processing input
这个是报错信息

**Comment by sengechupin** [comment]
大佬滴滴滴

**Comment by JeffMony** [comment]
试一下最新的版本

**Comment by sengechupin** [comment]
感谢大佬
