### ISSUE TITLE
有些网站把m3u8文件伪装成jpg，无法下载

### ISSUE THREAD

**Issue by iChengc** [JeffMony/VideoDownloader#55]
有些网站把m3u8文件伪装成jpg，导致无法下载，例如：https://videocut-upload-sz.oss-cn-shenzhen.aliyuncs.com/feedback/1692701348165_461da74d81124f9091e060e9a2f07c67.jpg?Expires=1692787748&OSSAccessKeyId=LTAIyIPluzf98f5v&Signature=FXMNhANEEF%2FVwXT7dAq3Ak%2Bt%2BW8%3D

**Comment by iChengc** [comment]
真实下载的文件
![1692701348165_461da74d81124f9091e060e9a2f07c67](https://github.com/JeffMony/VideoDownloader/assets/3106224/b49b0b2d-ca9a-4392-8a4c-a7000a9c55fc)

**Comment by JeffMony** [comment]
https://github.com/JeffMony/VideoDownloader/blob/master/library/src/main/java/com/jeffmony/downloader/VideoInfoParserManager.java#L94C1-L95C1  看下这个判断条件是不是走进去了？
