### ISSUE TITLE
是否考虑提供#EXT-X-BYTERANGE支持

### ISSUE THREAD

**Issue by BoyGK** [JeffMony/VideoDownloader#59]
对于如下格式的m3u8，下载貌似会有问题，是否考虑支持？
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-TARGETDURATION:4
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="test.mp4",BYTERANGE="869@0"
#EXTINF:3.003,
#EXT-X-BYTERANGE:86835@1669
test.mp4
#EXTINF:3.003,
#EXT-X-BYTERANGE:63869
test.mp4
#EXTINF:3.003,
#EXT-X-BYTERANGE:54610
test.mp4
#EXTINF:3.003,
#EXT-X-BYTERANGE:55245
test.mp4
省略。。。

**Comment by JeffMony** [comment]
好建议，会尽快支持，你这边有例子吗？给我一个测试看看

**Comment by BoyGK** [comment]
https://cf-st.sc-cdn.net/d/1awUye1IRuft6Nr1iIy1o.85.m3u8

**Comment by JeffMony** [comment]
https://github.com/JeffMony/VideoDownloader/commit/3fc2d40207f924681701c70f3244353720a2236d，已经支持了。
