### ISSUE TITLE
升级6.0.0新版后，同时下载多个短时长的mp4后，有的无法播放

### ISSUE THREAD

**Issue by mgxlili** [JeffMony/VideoDownloader#64]
设备：oppo手机 android 11
测试数据：
https://47.242.4.90/前任小叔他又宠又撩（89集）/第1集.mp4
https://47.242.4.90/前任小叔他又宠又撩（89集）/第2集.mp4
https://47.242.4.90/前任小叔他又宠又撩（89集）/第3集.mp4
https://47.242.4.90/前任小叔他又宠又撩（89集）/第4集.mp4
https://47.242.4.90/前任小叔他又宠又撩（89集）/第5集.mp4
https://47.242.4.90/前任小叔他又宠又撩（89集）/第6集.mp4
https://47.242.4.90/前任小叔他又宠又撩（89集）/第7集.mp4

下载后某些视频无法播放并且是随机的，有时候是第1集不能播放，有时候是第4集无法播放。
但是如果使用5.8.0没有该现象。

**Comment by JeffMony** [comment]
无法播放有具体的日志吗？我好进一步分析一下

**Comment by mgxlili** [comment]
> 无法播放有具体的日志吗？我好进一步分析一下

日志补充：
升级依赖
api 'com.github.JeffMony:VideoDownloader:6.0.0'
api 'com.github.JeffMony:JeffVideoLib:2.5.0'

下载配置是关闭合并 merge=false

ijkplayer 播放相关报错
 Error (-10000,0)

fb8b078c234f04c0fc98d0c079d54d63.video'.(FFmpegErr=Invalid data found when processing input)
Failed to open
No audio nor video. Return EOF


----
5.8.0依赖
api 'com.github.JeffMony:VideoDownloader:5.8.0'
api 'com.github.JeffMony:JeffM3U8Lib:2.5.0'

**Comment by JeffMony** [comment]
新版本已经解决了此问题，多线程下载的问题
